### ISSUE TITLE
Missing ability to save part of the object

### ISSUE THREAD

**Issue by dantix** [rafbgarcia/angular-parse-wrapper#7]
When you overriding save method by this code 
https://github.com/rafbgarcia/angular-parse-wrapper/blob/master/src/parse-wrapper.js#L91-L102
there is no way left to make partial update of the object.

Can we come up with compromise on this issue?

**Comment by rafbgarcia** [comment]
Hi @dantix, thanks for looking for improvements on the library.

Please correct me if I'm wrong, what you mean is that there is no way to just save the object without executing line `94:99`, correct?

If so, that could be as simple as adding one more parameter like `saveOnly`, right?

**Comment by taivo** [comment]
I think this issue was fixed in commit 28271d8b61f90a5a19e924dc3ba14aaa3dd9d5f4 from pr #8 . In that commit, partial updates in the form of `save({attr1: val1, attr2: val2})` trigger partial conversions so attributes that are not part of the update do not become dirty and get saved.

**Comment by rafbgarcia** [comment]
Awesome, so I'm closing this one.
